---
title: Running Snakemake
subtitle: Running Snakemake locally and on the cluster
author: Per Unneberg
date: "26 May, 2026"
format:
  nbis-quarto-revealjs:
    footer: "Running Snakemake"
    code-block-height: 500px
    theme:
      - default
      - ../custom.scss
---

## Setup  {.unnumbered .unlisted}

```{r libs }
#| echo: false
#| eval: true
#| cache: false
library(ggplot2)
library(viridis)
bw <- theme_bw(base_size=24) %+replace%
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
theme_set(bw)
knitr::opts_knit$set(root.dir = "examples")
snakemake_version <- system("snakemake --version", intern=TRUE)
```

::::: {.columns}

:::: {.column width="70%"}

<!-- markdownlint-disable MD013 -->

- Examples with Snakefiles and code to run in
  [examples](https://github.com/NBISweden/workshop-snakemake-byoc/tree/main/lectures/running-snakemake/examples)
  subdirectory
- Snakefiles have file suffix `.smk`
- Code has been run with Snakemake version `r snakemake_version`
- Rules run `bwa mem` to map two samples to a reference

<!-- markdownlint-enable MD013 -->

::: {.fragment}

An example command we may want to run is

```{bash }
#| label: bwa-command-example
#| echo: true
#| eval: false
bwa mem -t 1 resources/ref.fa data/CHS.HG00512_1.fastq.gz \
    data/CHS.HG00512_2.fastq.gz | samtools view -b -o bam/CHS.HG00512.bam
```

:::

::::

:::: {.column width="30%"}

Input data:

```{bash }
#| echo: false
#| label: list-data-0
tree -L 3 data resources
```

Snakefiles:

```{bash }
#| label:  list-snakefiles
#| echo: false
ls bwa*.smk
```

::::

:::::

## Writing a `bwa mem` alignment Snakefile

Let's start by writing a Snakefile that runs an alignment with `bwa`.
The command we want to run is

```{bash }
#| label: bwa-command
#| echo: true
#| eval: false
bwa mem -t 1 resources/ref.fa data/CHS.HG00512_1.fastq.gz \
    data/CHS.HG00512_2.fastq.gz | samtools view -b -o bam/CHS.HG00512.bam
```

::: {.fragment}

Identify the input, output and the structure of the command:

:::

::: {.incremental}

output
: `bam/CHS.HG00512.bam`

input
: `resources/ref.fa`, `data/CHS.HG00512_1.fastq.gz`, and `data/CHS.HG00512_2.fastq.gz`

command
: `bwa mem -t 1 {input} | samtools view -b -o {output}`

:::

::: {.fragment}

Putting these in a Snakefile `bwa_mem_CHS_HG00512.smk` yields:

``` {python code=readLines("bwa_mem_CHS_HG00512.smk"), filename="bwa_mem_CHS_HG00512.smk"}
#| eval: false
#| label: bwa_mem_CHS_HG00512-1
```

:::

## Start with a dry run

::::: {.columns}

:::: {.column width="50%"}

- It is good practice to first perform a dry run (option `--dry-run`,
  short option `-n`) that tests the workflow without actually
  executing any commands
- We also print the shell commands for clarity (`--printshellcmds/-p`)
- By default the first rule in the Snakefile is run
- You can specify the Snakefile to run with option `--snakefile/-s`

::: {.fragment}

```{bash  }
#| label: snakemake-bwa_mem_CHS_HG00512_f1-1
#| eval: false
snakemake --snakefile bwa_mem_CHS_HG00512.smk \
          --dry-run --printshellcmds
```

:::

::::

:::: {.column width="50%"}

::::

:::::

## Start with a dry run

::::: {.columns}

:::: {.column width="50%"}

- It is good practice to first perform a dry run (option `--dry-run`,
  short option `-n`) that tests the workflow without actually
  executing any commands
- We also print the shell commands for clarity (`--printshellcmds/-p`)
- By default the first rule in the Snakefile is run
- You can specify the Snakefile to run with option `--snakefile/-s`

```{bash  }
#| label: snakemake-bwa_mem_CHS_HG00512_f1-2
#| eval: false
snakemake -s bwa_mem_CHS_HG00512.smk -n -p
```

::::

:::: {.column width="50%"}

::::

:::::

## Start with a dry run

::::: {.columns}

:::: {.column width="50%"}

- It is good practice to first perform a dry run (option `--dry-run`,
  short option `-n`) that tests the workflow without actually
  executing any commands
- We also print the shell commands for clarity (`--printshellcmds/-p`)
- By default the first rule in the Snakefile is run
- You can specify the Snakefile to run with option `--snakefile/-s`

```{bash  }
#| label: snakemake-bwa_mem_CHS_HG00512_f1-3
#| eval: false
snakemake -s bwa_mem_CHS_HG00512.smk -n -p
```

Note the reason the rule was run[^reason1]

::::

:::: {.column width="50%"}

```{bash}
#| label: snakemake-bwa_mem_CHS_HG00512_f2
#| echo: false
rm -f bam/CHS.HG00512.bam
snakemake -s bwa_mem_CHS_HG00512.smk -n -p
```

::::

:::::

[^reason1]: for Snakemake <7.12 use the `--reason/-r` option

::: {.notes}

Mention the reason the rule was rerun

:::

## Run the workflow

::::: {.columns}

:::: {.column width="50%"}

- It is good practice to first perform a dry run (option `--dry-run`,
  short option `-n`) that tests the workflow without actually
  executing any commands
- We also print the shell commands for clarity (`--printshellcmds/-p`)
- By default the first rule in the Snakefile is run
- You can specify the Snakefile to run with option `--snakefile/-s`

```{bash}
#| label: snakemake-bwa_mem_CHS_HG00512-run
#| eval: false
snakemake -s bwa_mem_CHS_HG00512.smk -c 1
```

Note the reason the rule was run[^reason2]

- Remove `-n` to run, also specifying the number of cores to use with
`-c`.

::::

:::: {.column width="50%"}

```{bash}
#| label: snakemake-bwa_mem_CHS_HG00512-run-output
#| echo: false
rm -f bam/CHS.HG00512.bam
snakemake -s bwa_mem_CHS_HG00512.smk -c 1
```

::::

:::::

[^reason2]: for Snakemake <7.12 use the `--reason/-r` option

::: {.notes}

Mention the reason the rule was rerun

:::

## Use wildcards to generalize workflow

::::: {.columns}

:::: {.column width="40%"}

The current Snakefile consists only of one rule that also is specific
to the `CHS.HG00512` sample. First, let's generalize the bwa rule
using wildcards:

``` {python code=readLines("bwa_mem_wildcard.smk"), filename="bwa_mem_wildcard.smk"}
#| label: bwa_mem_wildcard
#| eval: false
```

::::

:::: {.column width="60%"}

::: {.fragment}

Now, running Snakemake as before results in an error:

```{bash }
#| eval: true
#| echo: true
snakemake -s bwa_mem_wildcard.smk -n -p
```

:::

::: {.fragment}

As the error indicates, we could specify a target (e.g.
`bam/PUR.HG00731.bam`; note the use of the `--quiet/-q` option to
suppress information):

``` {bash }
snakemake -s bwa_mem_wildcard.smk -q -n bam/PUR.HG00731.bam
```

:::

::::

:::::

## Use pseudo-rules for default build targets

::::: {.columns}

:::: {.column width="50%"}

Better solution: use a *pseudo-rule* (typically called `all`) at the
*top* of the Snakefile, since if no target is provided at the command
line, Snakemake will use the first rule it encounters.

``` {python code=readLines("bwa_mem.smk"), filename="bwa_mem.smk"}
#| eval: false
#| label: bwa_mem_pseudo
```

::::

:::: {.column width="50%"}

::: {.fragment}

Running the default target (implicitly `all`) gives:

```{bash }
#| echo: false
rm -f bam/*.bam
```

```{bash}
snakemake -s bwa_mem.smk -n
```

:::

::::

:::::

## Some useful options

::::: {.columns}

:::: {.column width="50%"}

<h5>Forcing reruns</h5>

One can force regeneration of a single target with the `--force
(-f)` option, or all targets with `--forceall/-F`:

```{bash }
#| eval: false
snakemake -s bwa_mem.smk -f -c 1 -n bam/CHS.HG00512.bam
```

<div style="height: 1em;"></div>

::: {.fragment}

<h5>Rerun-incomplete and keep-going</h5>

When resuming a workflow it can be handy to add the
`--rerun-incomplete (--ri)` and `--keep-going (-k)` options:

```{bash }
#| label: snakemake-rerun-incomplete-workflow
#| eval: false
snakemake -s bwa_mem.smk -c 2 --ri -k
```

`--rerun-incomplete` takes care of unfinished jobs, e.g. Slurm
timeouts. If a job fails, `--keep-going` will try to finish as many
jobs as possible before terminating the workflow.

:::

::: {.fragment}

<h5>Printing the workflow dag and rulegraph</h5>

You can print the workflow DAG with `--rulegraph`, `--dag` or
`--filegraph` options:

``` {bash }
#| eval: false
snakemake -s bwa_mem.smk --rulegraph|--dag|--filegraph \
    | dot | display
```

:::

::::

:::: {.column width="50%"}

::: {.fragment}

``` {bash }
#| fig-format: svg
#| output: asis
#| echo: false
#| html-table-processing: none
echo '```{=html}'
snakemake -s bwa_mem.smk --rulegraph 2>/dev/null | dot -T svg | \
    grep -v "<!DOCTYPE" | grep -v "dtd"
echo '```'
```

``` {bash }
#| fig-format: svg
#| output: asis
#| echo: false
#| html-table-processing: none
echo '```{=html}'
snakemake -s bwa_mem.smk --dag 2>/dev/null | dot -T svg | \
    grep -v "<!DOCTYPE" | grep -v "dtd"
echo '```'
```

``` {bash }
#| fig-format: svg
#| output: asis
#| echo: false
#| html-table-processing: none
echo '```{=html}'
snakemake -s bwa_mem.smk --filegraph 2>/dev/null | dot -T svg | \
    grep -v "<!DOCTYPE" | grep -v "dtd" | \
    sed -e "s/width=\"217pt\" height=\"304pt\"/width=\"150pt\" height=\"200pt\"/g"
echo '```'
```

:::

::::

:::::

## Resources can be specified for rules

Rules can define arbitrary resources with the resources keyword. They
can be specified in the rule or via the command line. Revisit the
output of a dry run:

::: {.fragment}

``` {bash}
snakemake -s bwa_mem.smk bam/CHS.HG00512.bam -n -f --quiet progress
```

:::

::: {.fragment}

Note the `tmpdir` resources in the output. This is one of several
*standard resources*, which in addition include `mem`, `disk`,
`runtime` and `gpu`. The resources names are names to the Snakemake
scheduler, and are used by the scheduler to determine which jobs can
be executed at the same time. This allows us to fine-tune resource
requirements, in particularly useful on a HPC cluster.

:::

## Default resources can be given default values

The standard resources can be given default values and be explicitely
listed (and set with arguments) with the `--default-resources` option:

```{bash }
snakemake -f -n -s bwa_mem.smk bam/CHS.HG00512.bam \
          --default-resources mem_mb=2000 --quiet progress
```

::: {.fragment}

Resources related to `mem` and `disk` now have been assigned default
values.

:::

::: {.notes}

Point out that this can cause jobs to fail if they exceed the
specified resources

:::

## Fine-tune resources with rule-specific settings

Default resources apply to all rules, but you can set resources on a
rule by rule basis. This can be achieved with the `--set-resources`
option (syntax `RULE_NAME:RESOURCE=VALUE`). Similarly `--set-threads`
allows setting rule-specific thread values (syntax `RULE_NAME=VALUE`):

::: {.fragment}

```{bash }
#| label:  snakemake-set-resources
snakemake -F -n -s bwa_mem.smk --default-resources mem_mb=2000 \
          --set-resources bwa_mem_wildcard:runtime=1000 bwa_mem_wildcard:mem_mb=6000 \
          --set-threads bwa_mem_wildcard=4 -c 8 --quiet progress
```

:::

## Use snakemake [profiles][profiles] to configure execution

Profiles are YAML configuration files that apply to specific compute
environments and analyses. They allow setting default options.

```{yaml code=readLines("local/config.yaml"), filename="local/config.yaml" }
#| label: snakemake-local-profile
#| eval: false
```

::: {.fragment}

A profile can be called in different ways, for instance by setting the
option `--profile` to the name of the directory that holds the profile
YAML file:

```{bash }
#| echo: true
#| eval: false
snakemake -s bwa_mem.smk --profile local
```

:::

[profiles]: https://snakemake.readthedocs.io/en/stable/executing/cli.html#profiles

## Use [Snakemake plugins][plugins] for cluster jobs

[plugins]: https://snakemake.github.io/snakemake-plugin-catalog/index.html

```{bash}
#| echo: true
#| eval: false
snakemake --executor cluster-generic --default-resources --jobs N
```

```{yaml}
executor: slurm
default_resources: []
```

# Questions?  {.unnumbered .unlisted}
