# -*- snakemake -*-
rule all:
    input: expand("sleep_{i}.txt", i = [10, 90])

wildcard_constraints:
        sec = "\d+"

rule sleep:
    output: "shadow_sleep_{sec}.txt"
    threads: 1
    shadow: "minimal"
    shell: "for i in $(seq 1 {wildcards.sec}); do echo $i >> {output}; sleep 1; done"
