title: "NBIS snakemake bring-your-own-code (BYOC) workshop"
baseurl: /workshop-snakemake-byoc

# where things are
layouts_dir: ./workshop-common/layouts
includes_dir: ./workshop-common/includes
sass:
  sass_dir: ./workshop-common/sass

plugins:
  - jemoji

defaults:
  - values:
      logosnav: true

menu:
  - title: Overview
    url: index
  - title: Schedule
    url: schedule
  - title: Pre-course information
    url: precourse