project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - bestpractices-detail/index.qmd
    - running-snakemake/index.qmd
  pre-render:
    - scripts/prepare-data.sh
institute: NBIS
from: markdown+emoji
format:
  nbis-quarto-revealjs:
    theme:
      - default
    footer: Snakemake BYOC
    date: last-modified
    date-format: "DD-MMM-YYYY"
    embed-resources: false
    code-line-numbers: false
    center: false
    toc: true
    toc-depth: 1
    slide-level: 2
    slide-number: true
    preview-links: true
    chalkboard: false
    smaller: true
    highlight-style: gruvbox
    fig-height: 12
    fig-width: 10
    fig-align: center
    text-align: left
    width: 1280
    height: 720
    margin: 0.1
    navigation-mode: vertical
    reference-location: margin
    ultitle: true

csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
execute:
  echo: true
  warning: false
  cache: true
  include: true
  autodep: true
  eval: true
  error: true
  freeze: auto
knitr:
  opts_chunk:
    code-fold: false
    tidy: true
    comment-char: "#>"
    fig-format: svg
    engine.opts:
      dvisvgm.opts: --font-format=woff
      template: tikzfig.tex
extensions:
  - nbis-quarto
