project:
  render:
    - index.qmd
    - bestpractices-detail/index.qmd
    - running-snakemake/index.qmd
  pre-render:
    - scripts/prepare-data.sh
institute: NBIS
from: markdown+emoji
format:
  nbis-course-revealjs:
    theme:
      - custom.scss
    toc: true
    toc-depth: 1
    slide-level: 2
    slide-number: true
    preview-links: true
    chalkboard: false
    footer: Snakemake BYOC
    smaller: true
    highlight-style: gruvbox
    fig-height: 3
    fig-width: 3
    fig-align: center
    text-align: center
    width: 1050
    height: 700
    margin: 0.05
    navigation-mode: vertical
  nbis-course-logo-revealjs:
    theme:
      - custom.scss
    toc: true
    toc-depth: 1
    slide-level: 2
    slide-number: true
    preview-links: true
    chalkboard: false
    footer: Snakemake BYOC
    smaller: true
    highlight-style: gruvbox
    fig-height: 3
    fig-width: 3
    fig-align: center
    text-align: center
    width: 1050
    height: 700
    margin: 0.05
    navigation-mode: vertical
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
execute:
  echo: true
  warning: false
  cache: true
  include: true
  autodep: true
  eval: true
  error: true
  freeze: auto
knitr:
  opts_chunk:
    code-fold: false
    tidy: true
    comment-char: "#>"
    fig-format: svg
    engine.opts:
      dvisvgm.opts: --font-format=woff
      template: tikzfig.tex
extensions:
 path: nbis-course-quarto
