name: lectures

channels:
    - conda-forge
    - bioconda
    - defaults
    - r

dependencies:

    # Snakemake
    - snakemake=5.26.1

    # Jupyter
    - python=3.8
    - jupyter=1.0
    - pandas=1.0
    - rise=5.6
    - seaborn=0.10
    - rpy2=3.1

    # R and Xaringan
    - r-base=3.6
    - r-dplyr=1.0.2
    - r-ggplot2=3.3
    - r-kableextra=1.1
    - r-reticulate=1.16
    - r-xaringan=0.15
    - phantomjs=2.1

    # revealjs
    - r-revealjs
    - r-viridis
    - seqtk
