# -*- snakemake -*-
from snakemake.utils import validate
configfile: "config.yaml"
validate(config, "main.schema.yaml")

print(config)

rule sleep:
    output: "shadow_sleep_{sec, \d+}.txt"
    resources:
        runtime = lambda wildcards, attempt: attempt * config["sleep"]["runtime"],
        mem_mb = config["sleep"]["mem_mb"]
    threads: config["sleep"]["threads"]
    shadow: "minimal"
    shell: "for i in $(seq 1 {wildcards.sec}); do echo $i >> {output}; sleep 1; done"
