rule foo:
    output: "foo.txt"
    shell: "echo foo > {output}"

rule bar:
    input: "foo.txt"
    output: "bar.txt"
    shell: "cat {input} > {output}; echo bar >> {output}"

rule foobar:
    input: foo = "foo.txt", bar = "bar.txt"
    output: "foo.bar.txt"
    shell: "cat {input.foo} {input.bar} > {output}; echo foo.bar >> {output}"
