# Keys are mapped to CLI options, e.g., executor: slurm is mapped to
# --executor slurm
executor: slurm
restart-times: 0
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 60
use-conda: false
use-envmodules: true
rerun-incomplete: true
rerun-triggers:
  - mtime
default-resources:
  disk_mb: 1000
  mem_mb: 6000
  runtime: 240
  slurm_account: SLURM_ACCOUNT
  slurm_partition: pelle
set-resources:
  bwa_mem_wildcard:
    slurm_partition: fat
    runtime: 12h
  gpu_job:
      runtime: 5d
      mem_mb: 700000
      slurm_partition: gpu
      gpu: 1
      gpu_manufacturer: nvidia
      gpu_model: l40s
