rule foo:
    output: "{prefix, foo}.txt"
    shell: "echo {wildcards.prefix} > {output}"

rule bar:
    input: "foo.txt"
    output: "{prefix, [a-z]+}.txt"
    shell: "cat {input} > {output}; echo {wildcards.prefix} >> {output}"

rule foobar:
    input: foo = "foo.txt", bar = "bar.txt"
    output: "{prefix1}.{prefix2}.txt"
    shell: "cat {input.foo} {input.bar} > {output}; echo {wildcards.prefix1}.{wildcards.prefix2} >> {output}"
