# Import relevant modules
import pandas as pd

# Read metadata
metadata = pd.read_csv('metadata.tsv', sep = '\t')

# Define plate and barcode IDs
plates = metadata['plate_id'].unique().tolist()
samples = metadata['sample_id'].unique().tolist()

rule all:
    input:
        expand("{plate}.collected_QC.txt", plate = plates)

rule demultiplex:
    input:
        data = "{plate}.fastq.gz",
    output:
        expand("{{plate}}-{sample}.fastq.gz", sample = samples)

rule quality_controls:
    input:
        rules.demultiplex.output
    output:
        "{plate}-{sample}_fastqc.zip"

rule collect_results:
    input:
        expand("{{plate}}-{sample}_fastqc.zip", sample = samples)
    output:
        "{plate}.collected_QC.txt"
