---
title: Snakemake best practices
author: Per Unneberg
date: "27 May, 2026"
format:
  nbis-quarto-revealjs:
    footer: "Best practices"
    theme:
      - default
      - ../custom.scss
---

## Setup  {visibility="hidden" .unnumbered .unlisted}

```{r }
#| label: setup
#| echo: false
#| eval: true
#| cache: false
library(ggplot2)
library(viridis)
bw <- theme_bw(base_size=24) %+replace%
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))
theme_set(bw)
snakemake_version <- system("snakemake --version", intern=TRUE)
# knitr::opts_knit$set(root.dir = "project")
knitr::knit_hooks$set(inline = function(x) {
  prettyNum(x, big.mark=",")
})
```

- Examples based on more advanced Snakefiles and code to run
- All Snakefiles and code are available in code repository
[https://github.com/NBISweden/snakemake_best_practice/](https://github.com/NBISweden/snakemake_best_practice/)
- Code has been run with Snakemake version `r snakemake_version`

The best practice example workflow is a mapping and basic qc workflow
where snakemake best practices have been applied.

::: {.fragment}

#### Objective

The objective of the lecture is to provide an overview of some
advanced features and how to structure your code. Hopefully it can
give you some ideas for developing your workflow. The material can be
a bit overwhelming so see it as a smörgåsbord where you can pick
things to your liking.

:::

## [Snakemake best practices summary](https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html)

::: {.fragment}

Care about code quality
: Run the linter before publishing any workflow, asking questions on
  Stack Overflow or filing issues on Github.

:::

::: {.fragment}

Care about code readability
: 1. Apply the automatic formatter for Snakemake workflows, Snakefmt,
    before publishing it.
  2. Try to keep filenames short
  3. Try to keep Python code like helper functions separate from rules
  4. Use Snakemake's [semantic helper][semantic] functions to increase
     readability

[semantic]: https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#semantic-helpers

:::

::: {.fragment}

Ensure portability
: Annotate rules with versioned Conda or container environments.

:::

::: {.fragment}

Generate interactive reports
: Annotate final results for inclusion in Snakemake's automatic
  interactive reports

:::

::: {.fragment}

Enable configurability
: Configuration of a workflow should be handled via config files and,
  if needed, tabular configuration like sample sheets (either via
  Pandas or PEPs). Use such configuration for metadata and experiment
  information, **not for runtime specific configuration like threads,
  resources and output folders**. For those, just rely on Snakemake’s
  CLI arguments like `--set-threads`, `--set-resources`,
  `--set-default-resources`, and `--directory`.

:::

::: {.fragment}

Avoid duplication of efforts
: Make use of Snakemake wrappers whenever possible

:::

::: {.fragment}

Test your workflow continuously
: It is a good idea to add some minimal test data and configure Github
  Actions for continuously testing the workflow on each new commit.

:::

::: {.fragment}

Follow the standards
: Stick to a standardized structure.

:::

::: {.fragment}

Simplify maintenance
: Use Snakedeploy to simplify and automate the maintenance of your
  workflows.

:::

::: {.notes}

- not necessary to follow these guidelines - suggestions
- there is however a need to comply with format to publish workflow in
  snakemake workflow collection
- order of importance: structure, filenames > test > configuration > lint/format > wrappers
- if only snakemake were python

:::

## Use the linter

::::: {.columns}

:::: {.column width="50%"}

``` {python code=readLines("linting1.smk"), filename="linting1.smk"}
#| eval: false
#| label: linting1_smk
```

::::

:::: {.column width="50%"}

::: {.fragment}

```{bash }
#| label: snakemake-lint-1
#| echo: true
#| eval: true
snakemake --lint text -s linting1.smk
```

:::

::::

:::::

## Use the linter

::::: {.columns}

:::: {.column width="50%"}

``` {python code=readLines("linting2.smk"), filename="linting2.smk"}
#| eval: false
#| label: linting2_smk
```

::::

:::: {.column width="50%"}

::: {.fragment}

```{bash }
#| label: snakemake-lint-2
#| echo: true
#| eval: true
snakemake --lint text -s linting2.smk
```

:::

::::

:::::

## Use the code formatter

::::: {.columns}

:::: {.column width="50%"}

``` {python code=readLines("linting2.smk"), filename="linting2.smk"}
#| eval: false
#| label: linting2_snakefmt_smk
```

::::

:::: {.column width="50%"}

::: {.fragment}

```{bash }
#| label: snakemake-fmt-1
#| echo: true
#| eval: true
snakefmt - < linting2.smk
```

:::

::::

:::::

::: {.fragment}

::: {.callout-warning}

`snakefmt` modifies files inplace so either run with `--diff` or
`--compact-diff` to view changes, or write the output to stdout with
the construct above (`snakefmt - < Snakefile`).

:::

:::

## [Semantic helper][semantic] functions

New as of version 8.3.0

::::: {.columns}

:::: {.column width="50%"}

`collect`
: alias for `expand`

`lookup`
: look up value in Python mapping (e.g., `config` object)

`branch`
: choose different input files based on a given conditional

`evaluate`
: evaluate an expression that contains wildcards

`exists`
: check whether a file exists

`prepend_param`
: prepend string to input files for commands that require repeated
  flags for every filename

`subpath`
: access subpath of input or output file. Useful for commands that
  require an output directory to be specified

Previously could be done with `lambda` expressions - semantic helpers
offer cleaner code. Check the docs for the full list of helpers!

::::

:::: {.column width="50%"}

``` {python code=readLines("semantic_helper.smk"), filename="semantic_helper.smk"}
#| eval: false
#| label: semantic_helper

```

::::

:::::

## Ensure portability with conda or container directive

::::: {.columns}

:::: {.column width="50%"}

``` {python code=readLines("call_variants.smk")[c(9:16,19:23)], filename="call_variants.smk"}
#| eval: false
#| attr-source: .numberLines startFrom="7"
```

```{bash }
#| label: snakemake-lint-3
#| echo: false
#| eval: true
snakemake --lint text -s linting2.smk
```

::::

:::: {.column width="50%"}

::: {.fragment}

``` {python code=readLines("call_variants.smk")[c(9:23)], filename="call_variants.smk"}
#| eval: false
#| attr-source: startFrom="7"
#| code-line-numbers: "9-10"
```

```{yaml, filename="envs/variant_calling.yaml"}
#| eval: false
channels:
  - conda-forge
  - bioconda
dependencies:
  - gatk=4.6.2.0
  - samtools
```

:::

::::

:::::

## Follow the standards and test your workflow

The repo <https://github.com/NBISweden/snakemake_best_practice> (`git
clone https://github.com/NBISweden/snakemake_best_practice.git`)
contains a workflow that follows (some of) the best practice
guidelines:

::::: {.columns}

:::: {.column width="50%"}

<div style="font-size:80%">

<!-- markdownlint-disable MD013 -->

```{bash }
#| label: snakemake-byoc-2026-bp-overview-dir
#| cache: true
#| eval: true
#| echo: false
cd project && tree -a -F -L 2 -I '.snakemake|LICENSE|.git|resources*references.fasta|resources*README.md|Dockerfile|environment.yaml|.gitignore|.gitattributes|.editorconfig|.pre-commit-config.yaml|config*config.yaml|config*samples.tsv|config*reads.tsv|.ipynb_checkpoints|.myprofile|logs|reports|results|interim|*.~undo-tree~|*.png|*.zip|*.html|.github|.gitkeep' | sed -e "s/\.\.\/\.\.\///g" | grep -v directories
```

<!-- markdownlint-enable MD013 -->

</div>

::::

:::: {.column width="50%"}

.test
: Designated test directory containing a small data set which ideally
  should suffice to run all or parts of the workflow. Useful for
  test-drived development.

README.md
: Describe what the workflow does and how to use it

workflow
: Contains top-level `Snakefile` that includes rules files stored in
  the `rules` sub-directory. NB: this is the main entry point to the
  workflow.

workflow/envs
: conda environment files loaded by rules

workflow/notebooks
: notebooks that can be called by the workflow

workflow/report
: workflow report templates

workflow/rules
: workflow rules

workflow/schemas
: schema files that describe and define configuration file and data formats

workflow/scripts
: scripts called by workflow

::::

:::::

::: {.notes}

Difficult for research projects that are always in some sort of test
phase

:::

## Generate interactive reports

```{bash }
#| echo: false
#| eval: true
mkdir -p reference
touch reference/genome.fa
mkdir -p data/chr1
touch data/chr1/aligned.bam
mkdir -p data/chr2
touch data/chr2/aligned.bam
mkdir -p data/chr3
touch data/chr3/aligned.bam
mkdir -p data/chr4
touch data/chr4/aligned.bam
```

::::: {.columns}

:::: {.column width="50%"}

```{bash }
#| label: snakemake-report
#| echo: true
#| eval: true
snakemake --report -s call_variants.smk
```

::::

:::: {.column width="50%"}

```{=html}
<iframe width="500" height="500" src="report.html" title="Report example"></iframe>
```

::::

:::::

## Snakemake wrappers

::::: {.columns}

:::: {.column width="50%"}

`wrapper` directive:

- Reusable wrapper scripts around e.g. command-line tools
- [The Snakemake Wrappers
  repository](https://snakemake-wrappers.readthedocs.io/en/stable/)
  contains a collection of reusable wrappers.
- accession format: `{version}/bio/{tool}/{command}`

[fastqc wrapper
documentation](https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/fastqc.html)

::::

:::: {.column width="50%"}

```{python filename="workflow/rules/qc.smk" }
#| label: qc-fastqc-wrapper
#| eval: false
#| echo: true
#| attr-source: startFrom="22"
#| code-line-numbers: "21-22"
rule qc_fastqc:
    """Run FastQC on input sequence files

    The rule uses a snakemake wrapper to run FastQC. See
    https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/fastqc.html

    The wildcard_constraints directive is used to limit the 'prefix'
    wildcard to strings starting with data/, followed by an arbitrary
    number of characters."""
    output:
        html="results/qc/fastqc/{prefix}.gz.html",
        zip="results/qc/fastqc/{prefix}.gz_fastqc.zip",
    input:
        "{prefix}.gz",
    wildcard_constraints:
        # Assume input reads always live in data/.+
        prefix="data/.+",
    threads: 1
    log:
        "logs/qc/fastqc/{prefix}.gz.log",
    wrapper:
        "0.78.0/bio/fastqc"
```

::::

:::::

## Pre-commit - for the git power user {.smallest}

::::: {.columns}

:::: {.column width="50%"}

[Pre-commit](https://pre-commit.com) is a "framework for managing and
maintaining multi-language pre-commit hooks".

##### 1. Write a config file

:::{style="height: 1em;"}

:::

##### 2. Run manually

Run manually on single files:

```{bash }
#| label: pre-commit-run-manual
#| echo: true
#| eval: false
pre-commit run --files filename
```

If the results are not to your liking, you can just check out the old
version with `git checkout filename`.

Or run on all staged files with `pre-commit run` (or just
`pre-commit`).

::: {.fragment}

With [Git hooks](https://git-scm.com/docs/githooks) you can automate
the process of identifying simple issues before submission to code
review.

##### 3. Install git hooks

```{bash }
#| label: pre-commit
#| eval: false
pre-commit install
```

This will run pre-commit everytime you commit code.

:::

::::

:::: {.column width="50%"}

```{python, filename=".pre-commit-config.yaml" }
#| label: pre-commit-config
#| eval: false
#| echo: true
#| highlight: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
  - repo: https://github.com/snakemake/snakefmt
    rev: v2.0.0
    hooks:
      - id: snakefmt
  - repo: local
    hooks:
      - id: lint
        name: Snakemake lint
        entry: snakemake --lint text
        language: system
        files: ''
```

::::

:::::

## Github actions for continuous integration

::::: {.columns}

:::: {.column width="50%"}

[Snakemake github
action](https://github.com/snakemake/snakemake-github-action) allows
running the test suite **on GitHub** to make sure commits and pull
requests don't break the workflow.

#### Activation and configuration

- to activate actions, add a GitHub actions configuration file to the
  directory `.github/workflows`
- the `on` directive configures when the actions should be run
- `jobs` defines `steps` that run (e.g, linting, testing)
- on GitHub, navigate to `Actions` to view the results of a run

#### Example configuration file

The example configuration defines two separate jobs:

1. `Linting`: lints the workflow with `snakemake --lint`
2. `Testing`: runs the workflow on test data in `.test` and tests
   report generation

::::

:::: {.column width="50%"}

<!-- markdownlint-disable MD013 -->

```{python, filename=".github/workflows/main.yaml" }
#| label: github-actions
#| eval: false
#| echo: true
#| highlight: false
name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches_ignore: []

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Lint workflow
      uses: snakemake/snakemake-github-action@v2
      with:
        directory: .
        snakefile: workflow/Snakefile
        args: "--lint"

  Testing:
    runs-on: ubuntu-latest
    needs: Linting
    steps:
    - name: Checkout code (and submodules if necessary)
      uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Test workflow (local test data)
      uses: snakemake/snakemake-github-action@v2
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--use-conda --show-failed-logs -j 10 --conda-cleanup-pkgs"
    - name: Test report
      uses: snakemake/snakemake-github-action@v2
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--report report.zip"
```

<!-- markdownlint-enable MD013 -->

::::

:::::

# Questions?  {.unnumbered .unlisted}
