rule foo:
    output: "{prefix}.txt"
    wildcard_constraints:
        prefix = "foo"
    shell: "echo {wildcards.prefix} > {output}"

rule bar:
    wildcard_constraints:
        prefix = "[a-z]+"
    input: "foo.txt"
    output: "{prefix}.txt"
    shell: "cat {input} > {output}; echo {wildcards.prefix} >> {output}"

rule foobar:
    input: foo = "foo.txt", bar = "bar.txt"
    output: "{prefix1}.{prefix2}.txt"
    shell: "cat {input.foo} {input.bar} > {output}; echo {wildcards.prefix1}.{wildcards.prefix2} >> {output}"
